### ISSUE TITLE
Please upgrade just_audio pub requirements

### ISSUE THREAD

**Issue by jinfagang** [themadmrj/chat_ui_kit#11]
It's too low and some basic package will conflict:

```
and just_audio >=0.3.0 <0.7.0-nullsafety.0 then image >=2.1.18 <3.0.0-nullsafety.0.
And because chat_ui_kit >=1.1.5 depends on just_audio ^0.6.13 and image >=2.1.14 <3.0.0-nullsafety.0 depends on xml ^4.2.0, if karyo from git and chat_ui_kit >=1.1.5 then xml ^4.2.0.
```
Some mordern pakcage already using latest package. But just_audio inside this repo doesn't update yet.

It still needs some lower basic lib which conficts with other mordern lib

**Comment by themadmrj** [comment]
Do you mean upgrading to null safety? That would also require migrating this package to null safety, which is planned but sadly not right now.

**Comment by jinfagang** [comment]
@themadmrj My project also do not have null safety, but it doesn't matter you using package with null safety...
Just upgrade and make your lib compilable is OK

**Comment by themadmrj** [comment]
You are right about being able to use a null safe package in a project that has not migrated yet. However, since this library also depends on [flutter_video_info](https://github.com/anandnet/flutter_video_info/issues/12), I cannot migrate just yet. If you cannot wait and want a faster migration, you can clone the package, migrate it, and I'll change the `flutter_video_info` dependency to your git url.

**Comment by themadmrj** [comment]
Null safe version published in pre-release, until all dependencies are safe.
See 1.2.0-nullsafety.0.
