### ISSUE TITLE
MessagesListController not able to clear items when enter chatPage again from another chatid

### ISSUE THREAD

**Issue by luohao123** [themadmrj/chat_ui_kit#21]
Here is my code:

```dart
gLogger.i("init controller items: ${_controller.items.length}");
    _controller.items.clear();
    _controller.notifyChanges();
    _chatBloc.fetchLocalMsgsForSession(_chat.id);
    subscription = _chatBloc.crtChatMsgs.listen((event) {
      _controller.addAll(event);
      _controller.notifyChanges();
      gLogger.i("now controller items: ${_controller.items.length}");
    });
```

this is inside my `initState` function, so I want clear items every time enter a new chatPage. But it doesn't do this. 

Normally, first log should be 0, and every time `crtChatMsgs` only fetechs 25 msgs from local. So everytime it enters chatPage, it should be 25 msgs.

However, first time:

![image](https://user-images.githubusercontent.com/49749220/116710466-5f46d200-aa04-11eb-9676-27257c4fd82e.png)

this is normal, then I switch to another chatid (another chat page):

![image](https://user-images.githubusercontent.com/49749220/116710691-a0d77d00-aa04-11eb-832d-92eb8b61bc5a.png)

As u can see, second time the msg doesn't clear at all. It becomes 50, double of them. Normally, it should be fresh 25 msgs.

And the UI actually doesn't updated still contains data from previous chatid.

What could be the reason?

(I am new to flutter maybe I did something wrong but this lib is really useful, so I use it)

**Comment by themadmrj** [comment]
First off, I'm not sure I understand your flow. Usually to leave a ChatScreen, the user will go BACK and therefore pop the destination from the stack to return to ChatsScreen (the list of Chats), therefore also disposing the controller.

When you call `_controller.items.clear();`, it has nothing to do with the library. You're simply calling `clear()` on a dart list. The fact that you have 50 items instead of 25 after that indicates that you have a problem somewhere else, since clear() cannot fail. I suspect that it has something to do with the way you handle your controller. When accessing a new ChatScreen, you should create a new controller instance (which resets the items).

**Comment by luohao123** [comment]
Event I add a clear at dispose!!!!!! 
this is really bug!!

![image](https://user-images.githubusercontent.com/49749220/116712842-d67d6580-aa06-11eb-9471-0fff3a6014a3.png)

**Comment by luohao123** [comment]
@themadmrj  I am currently found, even I re-enter same chatid page, the msg still increase, rather than first clear and then add only 25 msgs.

And my observation is that seems the stream call twice..... But I don't know why it called twice... I am gonna to cry about this.

Here is my code of navigate to detail:

```
final cp =
        ChatScreen(ChatScreenArgs(chat: chat, chatBloc: widget.chatBloc));
    var res = await Navigator.of(context)
        .push(CupertinoPageRoute(builder: (context) => cp));
```

**Comment by themadmrj** [comment]
Good old debugging process, just add `print` everywhere and eventually you'll find the problem!
Closing since solved/not related to library.

**Comment by luohao123** [comment]
I solved my problem, thanks!

**Comment by luohao123** [comment]
For future people might got this issue... I dont' plan to tell u guys..
