### ISSUE TITLE
Hi, thanks for the work, may I ask a question?

### ISSUE THREAD

**Issue by luohao123** [themadmrj/chat_ui_kit#22]
Hi, this lib seems very promising. I tried integrate this lib to my project. Here is my last question:

How to customize my input bar at ChatPage? To be more specificly, I just need customize the send button (default it's Flatbutton seems not fit well with my customers). And I want add a send voice button along side with it.

Is there anyway to make it? thanks in advance!

**Comment by themadmrj** [comment]
As you can see, `MessageInput` is just a separate Widget, like any other Flutter Widget. The example in the library aims more to show you how to implement `MessageInputTypingHandler`, rather than giving a detailed UI Widget. Therefore, you can (and should) create your own Widget with a button that can fit your liking. Just remember to implement `MessageInputTypingHandler` to benefit from automatic typing mechanisms. One of the screenshots in the readme already shows a completely different `MessageInput` Widget.

**Comment by themadmrj** [comment]
Did it answer your question? If so, the topic can be closed.
