### ISSUE TITLE
[Help]: Best pratices with database

### ISSUE THREAD

**Issue by Abacaxi-Nelson** [themadmrj/chat_ui_kit#3]
Hello
Thanks for the lib, it's awesome.

Adding a message, following your example doesn't need a refresh (your plugin does it):

```dart
void onMessageSend(String text) {
    _controller.insertAll(0, [
      ChatMessage(
          author: _currentUser,
          text: text,
          creationTimestamp: DateTime.now().millisecondsSinceEpoch)
    ]);
  }
```

Using Firestore, i just need to push the message on my collection (awesome cause dont need to await firestore, the app is smooth).

_Do you have some guidance for incoming message (So Firestore is updated by other member) ? how to update only the controller ?_ 

im using Riverpod, and only way i have is to subscribe to a stream and update whole component on Firestore update.
Im looking for a way, to simpy to do ```_controller.insertAll(0, [ ]);``` for incoming messages..

---------
 
About custom message like _XXX is typing_ , do you have some pointer to use them (With db) ?

Thank you,
Great plugin !
Nelson

**Comment by themadmrj** [comment]
> Adding a message, following your example doesn't need a refresh (your plugin does it):
> 
> ```dart
> void onMessageSend(String text) {
>     _controller.insertAll(0, [
>       ChatMessage(
>           author: _currentUser,
>           text: text,
>           creationTimestamp: DateTime.now().millisecondsSinceEpoch)
>     ]);
>   }
> ```
> 
 
Is there a question here? Not sure I get it...

> _Do you have some guidance for incoming message (So Firestore is updated by other member) ? how to update only the controller ?_

> im using Riverpod, and only way i have is to subscribe to a stream and update whole component on Firestore update.
> Im looking for a way, to simpy to do `_controller.insertAll(0, [ ]);` for incoming messages..

Not sure where the problem is there either. You basically have to listen to some sort of service (I use a custom websocket based service) that has to notify you of any incoming messages. This notification should then trigger `controller.insertAll()` to update the UI.

> About custom message like _XXX is typing_ , do you have some pointer to use them (With db) ?

You're supposed to send an event to other chat members. With websockets, I send an event to my backend, which relays it the all other chat members, which can then display it in the UI. With a firebase backed DB, I get you have to create a database field that contains the list of typing members. You then only have to listen to that specific field and also update it according to the events emitted by `MessageInput`. Hope that helps. For none package related questions, please ask your question on StackOverflow :)

**Comment by Abacaxi-Nelson** [comment]
for people using firestore.
this code listen to changes in collection, to update UI when new chat come:
```dart
FirebaseFirestore.instance.collection('Chats').snapshots().listen((querySnap) async {
      final List<ChatWithMembers> _chats = [];
      for (final change in querySnap.docChanges) {
        if (change.type == DocumentChangeType.added) {
          final members = await getMembers(change.doc.data());
          _chats.add(ChatWithMembers.fromJson(change.doc.data(), change.doc.id, members));
        }
        //print('doc 2 => ${change.type}');
        //print('doc 2 => ${change.doc.id}');
        //print('doc 2 => ${change.doc.data()}');
      }
      _model.controller.insertAll(0, _chats);
    }).onError((e) => print(e));
```
