### ISSUE TITLE
[feature request] Stylizing message input

### ISSUE THREAD

**Issue by Dreamersoul** [themadmrj/chat_ui_kit#9]
There is no mention of stylizing the input provided with the library, even digging through the code it is apparent that this is not yet implemented [link](https://github.com/themadmrj/chat_ui_kit/blob/master/lib/src/widgets/core/message_input.dart).
Thank you

**Comment by themadmrj** [comment]
![input](https://user-images.githubusercontent.com/11475495/109521692-db2ca880-7aad-11eb-8005-b3b1ae80e874.PNG)
![input2](https://user-images.githubusercontent.com/11475495/109521693-dbc53f00-7aad-11eb-9385-1082a08e1e5a.PNG)

The first picture is how `MessageInput` looks like with the current Widget, as demonstrated in the example app.
The second picture is an example of how I made it look like in one of my own projects.
This is just to point out that for something as project specific, there are way too many possibilities to customize `MessageInput`. That's why the current implementation is ment to give you an example which uses `MessageInputTypingHandler`. You should copy `MessageInput` and design your own specific UI, given the example. There is no point trying to cover all the possibilities. We would never be done!

**Comment by Dreamersoul** [comment]
ohh perfect thanks for the response. That makes sense now. 

There is no need for a PR just to do styling... maybe pointing that out in the readme could be beneficial (I will explore that soon). I am in the process of exploring the possibility of migrating from `dash chat` to this library. Once I get more familiar with the code I think I will post a PR to the readme :)

**Comment by themadmrj** [comment]
Yes I initially wrote this library exactly because DashChat lacked too many important things, such as typing handling, modular Model, group conversations, adaptive containers etc.
I thought the first lines in the read explained that?

> This Flutter package provides you with a base structure as well as a set of tools that allow you to quickly build up a modern chat UI. Instead of trying to come up with all in one Widgets that meet everyone's expectations, you are given helpers that are meant to be used as examples and customized at will.

**Comment by Dreamersoul** [comment]
my problem with dash chat is that it is not actively maintained now and I rely on it in production... This looked like an actively maintained package that had a better system with models and everything
